version: 1
disable_existing_loggers: false

formatters:
  custom:
    format: "%(name)s [%(levelname)s]: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: custom
    stream: ext://sys.stdout


root:
  level: DEBUG
  handlers: [console]